server:
  port: 8088

spring:
  application:
    name: clinical-service
  datasource:
    url: jdbc:postgresql://localhost:5432/clinical_db
    username: clinical_db
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
