server:
  port: 8090

spring:
  application:
    name: health-metrics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/health_metrics_db
    username: health_metrics_db
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
