server:
  port: 8093

spring:
  application:
    name: document-service
  datasource:
    url: jdbc:postgresql://localhost:5432/document_db
    username: document_db
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
