server:
  port: 8084

spring:
  application:
    name: organization-service
  datasource:
    url: jdbc:postgresql://localhost:5432/organization_db
    username: organization_db
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
